In [21]:
import numpy as np

   This is my initial eigenvector score for pages.

In [22]:
x0 = np.array([1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
print(x0)

[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]


This is my graph of pages with links represent in matrix and modified this matrix to fix sinks and teleporting.

In [23]:
p = np.array([[1/60, 7/15, 7/15, 1/60, 1/60, 1/60],
               [1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
               [19/60, 19/60 , 1/60, 1/60, 19/60, 1/60],
               [1/60, 1/60, 1/60, 1/60, 7/15, 7/15],
               [1/60, 1/60, 1/60, 7/15, 1/60, 7/15],
               [1/60, 1/60, 1/60, 11/12, 1/60, 1/60]])

print(p)

[[0.01666667 0.46666667 0.46666667 0.01666667 0.01666667 0.01666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.31666667 0.31666667 0.01666667 0.01666667 0.31666667 0.01666667]
 [0.01666667 0.01666667 0.01666667 0.01666667 0.46666667 0.46666667]
 [0.01666667 0.01666667 0.01666667 0.46666667 0.01666667 0.46666667]
 [0.01666667 0.01666667 0.01666667 0.91666667 0.01666667 0.01666667]]


Instead of using manual method power iteration to reach steady state im used loop of 16 iteration,    
and im used this number because is enough number of iterations to reach steady state.

In [24]:
page_rank_score = x0

for i in range(16):
    page_rank_score = np.dot(page_rank_score, p)

print(page_rank_score)

print("\n- Pages sorted based on the page rank with link analysis without content of each page:\n")
for i, index in enumerate(np.argsort(page_rank_score)[::-1], start=1):
    print(f"Page{index + 1} with score: {page_rank_score[index]:.6f}")

[0.03724891 0.05402154 0.04154868 0.37500616 0.20598094 0.28619378]

- Pages sorted based on the page rank with link analysis without content of each page:

Page4 with score: 0.375006
Page6 with score: 0.286194
Page5 with score: 0.205981
Page2 with score: 0.054022
Page3 with score: 0.041549
Page1 with score: 0.037249


Im divide each element in the query_occurrences array to the sum of the elements in the query_occurrences,     
 because I need the score of each document normalized between 0 to 1 to apply this score to the final result.

In [25]:
query_occurrences = np.array([1, 3, 2, 4, 5, 0])
query_score = query_occurrences / np.sum(query_occurrences)

print(query_score)

print("\n- Pages sorted based on the page content relevance to the query:\n")
for i, index in enumerate(np.argsort(query_score)[::-1], start=1):
    print(f"Page{index + 1} with score: {query_score[index]:.2f}")

[0.06666667 0.2        0.13333333 0.26666667 0.33333333 0.        ]

- Pages sorted based on the page content relevance to the query:

Page5 with score: 0.33
Page4 with score: 0.27
Page2 with score: 0.20
Page3 with score: 0.13
Page1 with score: 0.07
Page6 with score: 0.00


### In this approch im consider the query relevence after reach the steady state for each page in the graph 
Im calculate the final score for the query with each page based on the content, and im take in the consideration the pageRank    
 to modify the final result.

Im multiply each of score (pageRank and queryRelvance Score) to the weight, and this weight depend on the IR system and usecases,   
but for test purposes im assign 0.7 to the content of each document (query relevance) and 0.3 to the pageRank.

In [26]:
page_rank_weight = 0.3
query_relvance_weight = 0.7

final_score_results = page_rank_weight * page_rank_score + query_score * query_relvance_weight

print(final_score_results)

print("\n- Pages sorted based on the page content relevance to the query and consider the page rank on the score:\n")
for i, index in enumerate(np.argsort(final_score_results)[::-1], start=1):
    print(f"Page{index + 1} with score: {final_score_results[index]:.6f}")

[0.05784134 0.15620646 0.10579794 0.29916852 0.29512761 0.08585813]

- Pages sorted based on the page content relevance to the query and consider the page rank on the score:

Page4 with score: 0.299169
Page5 with score: 0.295128
Page2 with score: 0.156206
Page3 with score: 0.105798
Page6 with score: 0.085858
Page1 with score: 0.057841


In this approach im consider query relevance iteratively to update the score for each iteration   
It allows for continuous refinement of the scores based on both link analysis and query relevance.

In [27]:
page_rank_weight = 0.3
query_relvance_weight = 0.7

final_score_results = x0

for i in range(16):
    final_score_results = page_rank_weight * final_score_results + query_score * query_relvance_weight

print(final_score_results)

print("\n- Pages sorted based on the page rank with link analysis without content of each page:\n")
for i, index in enumerate(np.argsort(final_score_results)[::-1], start=1):
    print(f"Page{index + 1} with score: {final_score_results[index]:.6f}")

[6.66666671e-02 2.00000000e-01 1.33333333e-01 2.66666666e-01
 3.33333333e-01 7.17445350e-10]

- Pages sorted based on the page rank with link analysis without content of each page:

Page5 with score: 0.333333
Page4 with score: 0.266667
Page2 with score: 0.200000
Page3 with score: 0.133333
Page1 with score: 0.066667
Page6 with score: 0.000000
